name: paramak

channels:
  - conda-forge
  - cadquery

dependencies:
  - pytest
  - plotly
  - scipy
  - numpy
  - matplotlib
  - pillow
  - cadquery=2.1
  - moab
  - neutronics-material-maker
  - remove_dagmc_tags
  - plasmaboundaries
  - pip:
    - sympy
    - sphinx-autodoc-typehints
    - sphinxcadquery
    - defusedxml
    