# Python CircleCI 2.0 configuration file
##
# Check https://circleci.com/docs/2.0/language-python/ for more details


version: 2
jobs:
  build-docker:
    environment:
      IMAGE_NAME: openmcworkshop/paramak
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t $IMAGE_NAME:rem .
            docker save -o image/my_image.tar $IMAGE_NAME:rem
      # https://support.circleci.com/hc/en-us/articles/360019182513-Build-a-Docker-image-in-one-job-and-use-it-in-another-job
      - persist_to_workspace:
          root: /image
          paths : my_image.tar

  test:
    docker:
      - image: openmcworkshop/paramak:rem
    steps:
      - run:
          name: run utils tests
          command: 
            echo 'coucou'

workflows:
  version: 2
  build-test:
    jobs:
      - build-docker
      - test:
          requires:
            - build-docker
