# Python CircleCI 2.0 configuration file
##
# Check https://circleci.com/docs/2.0/language-python/ for more details


version: 2
jobs:
  build-docker:
    environment:
      IMAGE_NAME: openmcworkshop/paramak
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t $IMAGE_NAME:rem .
            docker save $IMAGE_NAME:rem | gzip > my_image.tar.gz
      # https://support.circleci.com/hc/en-us/articles/360019182513-Build-a-Docker-image-in-one-job-and-use-it-in-another-job
      - persist_to_workspace:
          root: .
          paths : my_image.tar.gz

  test:
    environment:
      IMAGE_NAME: openmcworkshop/paramak
    machine: true
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Setup Docker environment
          command: |
            docker load -i my_image.tar.gz
      - run:
          name: Run container
          command: |
            docker run $IMAGE_NAME:rem
      - run:
          name: run utils tests
          command:
            pytest tests/test_utils.py -v --cov=paramak --cov-report term --cov-report html:htmlcov --cov-report xml --junitxml=test-reports/junit.xml

workflows:
  version: 2
  build-test:
    jobs:
      - build-docker
      - test:
          requires:
            - build-docker
