# Python CircleCI 2.0 configuration file
##
# Check https://circleci.com/docs/2.0/language-python/ for more details


version: 2
jobs:
  build-docker:
    environment:
      IMAGE_NAME: openmcworkshop/paramak
    docker:
      - image: circleci/buildpack-deps:stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build Docker image
          command: |
            docker build -t $IMAGE_NAME:$CIRCLE_SHA1 .
      - run:
          name: Publish Docker Image to Docker Hub
          command: |
            echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            
            docker push $IMAGE_NAME:$CIRCLE_SHA1

  test:
    environment:
      IMAGE_NAME: openmcworkshop/paramak
    docker:
      - image: $IMAGE_NAME:$CIRCLE_SHA1
    steps:
      - run:
          name: run utils tests
          command: |
            cd .. && pytest tests/test_utils.py -v --cov=paramak --cov-report term --cov-report html:htmlcov --cov-report xml --junitxml=test-reports/junit.xml

workflows:
  version: 2
  build-test:
    jobs:
      - build-docker
      - test:
          requires:
            - build-docker
