# This yml file will trigger a Github Action on pushes to the main branch.
# This Action will build and upload a Docker image to Dockerhub
# https://github.com/marketplace/actions/publish-docker

name: dockerhub-publish-dependencies

on:
  push:
    branches:
    - develop  
    - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          dockerfile: DockerfileDependencies
          push: true
          tags: ukaea/paramak:dependances
          build-args: |
            cq_version=master
            compile_cores=2
            include_neutronics=true
      -
        name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
