
name: CI - Merge to Develop
on:  
  pull_request:    
    branches:
    - develop  
jobs:  
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # cadquery-version: [2.1]
        # include-neutronics: [true, false]

        include:
          - include-neutronics: true
            cadquery-version: 2.1
          - include-neutronics: false
            cadquery-version: 2.1

    steps:    
    - uses: actions/checkout@v1
    - name: Build and test with Docker - Cadquery Version = ${{ matrix.cadquery-version }}
      run: |
        docker build -t paramak --build-arg include_neutronics=${{ matrix.include-neutronics }} --build-arg cq_version=${{ matrix.cadquery-version}} --build-arg compile_cores=2 .
        docker run --rm paramak  /bin/bash -c "bash run_tests.sh include_neutronics=${{ matrix.include-neutronics }} && curl -s https://codecov.io/bash | bash"



# name: CI - Merge to main
# on:
#   pull_request:
#     branches:
#       - main
# jobs:
#   build:
#     runs-on: ubuntu-latest
#     strategy:
#       fail-fast: false
#       matrix:
#         # cadquery-version: [2.1, master]
#         # include-neutronics: [true, false]

#         include:
#           - include-neutronics: true
#             cadquery-version: master
#           - include-neutronics: false
#             cadquery-version: master
    
#     steps:
#     - uses: actions/checkout@v1
#     - name: Build and test with Docker - Cadquery Version = ${{ matrix.cadquery-version }}
#       run: |
#         docker build -t paramak --build-arg include_neutronics=${{ matrix.include-neutronics }} --build-arg cq_version=${{ matrix.cadquery-version}} --build-arg compile_cores=2 .
#         docker run --rm paramak  /bin/bash -c "bash run_tests.sh include_neutronics=${{ matrix.include-neutronics }} && curl -s https://codecov.io/bash | bash"