
name: CI
on:  
  pull_request:    
    branches:
    - develop  
    - main
jobs:  
  build:     
   runs-on: ubuntu-latest

   steps:    
   - uses: actions/checkout@v1
   - name: Build and test with Docker
     run: |
       docker build -t paramak --build-arg include_neutronics=true --build-arg cq_version=2.1 --build-arg compile_cores=2 .
       docker run --rm paramak  /bin/bash -c "cd .. && bash run_tests.sh && curl -s https://codecov.io/bash | bash"
