
name: CI - Develop
on:  
  pull_request:    
    branches:
    - develop  
jobs:  
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        cadquery-version: [2.1]
        include-neutronics: [true]

    steps:    
    - uses: actions/checkout@v1
    - name: Build and test with Docker
      run: |
        docker build -t paramak --build-arg include_neutronics=${{ matrix.include-neutronics }} --build-arg cq_version=${{ matrix.cadquery-version}} --build-arg compile_cores=2 .
        docker run --rm paramak  /bin/bash -c "bash run_tests.sh include_neutronics=${{ matrix.include-neutronics }} && curl -s https://codecov.io/bash | bash"
